import os

HUGGINGFACEHUB_API_TOKEN = 'yTP3OlllcDaiqmgcoxJghetYuF9Z05fj'
os.environ["HUGGINGFACEHUB_API_TOKEN"] = HUGGINGFACEHUB_API_TOKEN
# 20Y66IO4m8yVqc8SFodejVKVZAXiXKhN
print(HUGGINGFACEHUB_API_TOKEN)